import { useState } from "react";
import { api } from "../api";
import { Badge, Banner, fmt } from "../ui";

export default function WorkOrderCard({ wo, tech, onChanged, onError }) {
  const [editing, setEditing] = useState(false);
  const [rejecting, setRejecting] = useState(false);
  const [reason, setReason] = useState("");
  const [form, setForm] = useState({ title: wo.title, description: wo.description, priority: wo.priority });
  const [busy, setBusy] = useState(false);
  const isDraft = wo.status === "draft";

  const run = async (fn) => {
    if (!tech.trim()) return onError("Enter your name in the Technician field at the top first.");
    setBusy(true);
    try {
      await fn();
      setEditing(false);
      setRejecting(false);
      setReason("");
      await onChanged();
    } catch (e) {
      onError(e.message);
    } finally {
      setBusy(false);
    }
  };

  const save = () =>
    run(async () => {
      const body = { edited_by: tech.trim() };
      for (const k of ["title", "description", "priority"]) if (form[k] !== wo[k]) body[k] = form[k];
      if (Object.keys(body).length === 1) return;
      await api.editWorkOrder(wo.id, body);
    });

  return (
    <div className="card wo">
      <div className="wo-head">
        <h3>Work order #{wo.id}</h3>
        <span><Badge status={wo.status} /> <Badge status={wo.priority} /></span>
      </div>

      {wo.warnings.map((w, i) => <Banner key={i} kind="warn">{w}</Banner>)}

      {editing ? (
        <div className="form">
          <label>Title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label>
          <label>Description
            <textarea rows={8} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} />
          </label>
          <label>Priority
            <select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>
              {["low", "medium", "high", "critical"].map((p) => <option key={p}>{p}</option>)}
            </select>
          </label>
          <div className="row">
            <button disabled={busy} onClick={save}>Save changes</button>
            <button className="ghost" onClick={() => setEditing(false)}>Cancel</button>
          </div>
        </div>
      ) : (
        <>
          <p><strong>{wo.title}</strong></p>
          <pre className="wrap">{wo.description}</pre>
        </>
      )}

      {wo.status === "approved" && <p className="hint">Approved by {wo.decided_by} on {fmt(wo.decided_at)}. This order is locked.</p>}
      {wo.status === "rejected" && (
        <p className="hint">Rejected by {wo.decided_by} on {fmt(wo.decided_at)}. Reason: {wo.rejection_reason}</p>
      )}

      {isDraft && !editing && (
        <div className="row">
          <button className="ghost" onClick={() => { setForm({ title: wo.title, description: wo.description, priority: wo.priority }); setEditing(true); }}>Edit</button>
          <button disabled={busy} onClick={() => run(() => api.approve(wo.id, tech.trim()))}>Approve</button>
          <button className="danger" onClick={() => setRejecting(!rejecting)}>Reject</button>
        </div>
      )}

      {isDraft && rejecting && (
        <div className="form">
          <label>Reason for rejection
            <input value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Required" />
          </label>
          <button className="danger" disabled={busy || reason.trim().length < 3}
            onClick={() => run(() => api.reject(wo.id, tech.trim(), reason.trim()))}>Confirm rejection</button>
        </div>
      )}
      <p className="hint">Draft generated by AI; nothing is approved until a technician approves it.</p>
    </div>
  );
}
